name: "Deploy Infrastructure"
on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [opened, reopened, synchronize]
  push:
    branches: main

env:
  environment: "qa"

jobs:
  Terraform-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: "eu-west-2"
          role-to-assume: "arn:aws:iam::510769981514:role/GitHubActionsDeploymentRole"

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: |
          if [ -d ".terraform" ]; then
            echo "Removing .terraform..."
            rm -rf .terraform
          fi
          terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -out tfplan
